---
title: "Mental Accounting in College: Students and 'Free Money'"
author: "Connor Woods"
date: "April 2, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, cache=TRUE, 
                      fig.width=7, fig.height=3, fig.align = "center")
library(readr)
library(dplyr)
library(ggplot2)
library(lubridate)
```

*Spring Semester Dates*
Campus Open: 1/20/19, Start: 1/22/19, End: 5/8/19, Campus Closed: 5/20/19

*Fall Semester Dates*
Campus Open: 8/31/19 Start: 9/3/19, End: 12/11/19, Campus Closed: 12/21/19

```{r}

flex_data <- read_csv("flex_data.csv") 
flex_data <- flex_data %>% mutate(Time = mdy_hm(Time)) %>% mutate(Week = epiweek(Time)) %>% rename(AmountSpent=Price)
flex_data <- flex_data %>% filter(Time >= '2019-01-20' & Time <= '2019-12-19') %>%  filter(AmountSpent > 0)

```


```{r}
#Graph adjustments 
theme_update(text = element_text(size=20))
theme_update(plot.title = element_text(hjust = 0.5))

#Transactions by week
springtrans <- flex_data %>% filter(Time <= '2019-5-19') %>% mutate(Week = Week-3) %>% filter(Week!=1 & Week!=9 & Week!=10 & Week!=17)
falltrans <- flex_data %>% filter(Time >= '2019-9-1') %>% mutate (Week = Week-35) %>% filter(Week!=1 & Week!=8 & Week!=13 & Week!=16)

springtransactions <- springtrans %>% group_by(Week) %>% summarize(Transactions = n()) %>% rbind(c(1,0), c(9,0), c(10,0), c(17,0)) %>% arrange(Week) 
falltransactions <- falltrans %>% group_by(Week) %>% summarize(Transactions = n()) %>% rbind(c(1, 0), c(8,0), c(13,0), c(16,0)) %>% arrange(Week)

ggplot(springtransactions) + geom_bar(aes(x=Week, y=Transactions), stat='identity', fill = "navy", color = "black") + ggtitle("Spring Transactions") + scale_x_continuous(breaks = 1:17)
ggplot(falltransactions) + geom_bar(aes(x=Week, y=Transactions), stat='identity', fill = "steelblue", color = "black") + ggtitle("Fall Transactions") + scale_x_continuous(breaks = 1:16)

```

```{r}
#Purchases by week
springpurchases <- springtrans %>% group_by(Week) %>% summarize(TotalPurch = sum(AmountSpent)) %>% rbind(c(1,0), c(9,0), c(10,0), c(17,0)) %>% arrange(Week) 
fallpurchases <- falltrans %>% group_by(Week) %>% summarize(TotalPurch = sum(AmountSpent)) %>% rbind(c(1, 0), c(8,0), c(13,0), c(16,0)) %>% arrange(Week)

ggplot(springpurchases) + geom_bar(aes(x=Week, y=TotalPurch), stat='identity', fill = "navy", color = "black") + ggtitle("Spring Expenditures") + scale_x_continuous(breaks = 1:17) + ylab("Expenditures ($)")
ggplot(fallpurchases) + geom_bar(aes(x=Week, y=TotalPurch), stat='identity', fill = "steelblue", color = "black") + ggtitle("Fall Expenditures") + scale_x_continuous(breaks = 1:16) + ylab("Expenditures ($)")

```


```{r}
#Amount Spent Per Transaction
springppt <- springtrans %>% group_by(Week) %>% summarize(TotalTrans = n(), TotalPurch = sum(AmountSpent)) %>% mutate(PPT = TotalPurch/TotalTrans)
fallppt <- falltrans %>% group_by(Week) %>% summarize(TotalTrans = n(), TotalPurch = sum(AmountSpent)) %>% mutate(PPT = TotalPurch/TotalTrans)

ggplot(springppt) + geom_bar(aes(x=Week, y=PPT), stat='identity', fill = "navy", color = "black") + ggtitle("Spring Expenditures Per Transaction") + scale_x_continuous(breaks = 1:17) + scale_y_continuous(breaks = 1:5) + ylab("Dollars Per Transaction")
ggplot(fallppt) + geom_bar(aes(x=Week, y=PPT), stat='identity', fill = "steelblue", color = "black") + ggtitle("Fall Expenditures Per Transaction") + scale_x_continuous(breaks = 1:16) + scale_y_continuous(breaks = 1:6) + ylab("Dollars Per Transaction")
```

```{r}
#Creation of consistent null dataframes

sprnullconsistent <- data.frame("Week"=1:17, "Transactions"= c(0,sum(springppt$TotalTrans)/13,sum(springppt$TotalTrans)/13,sum(springppt$TotalTrans)/13,sum(springppt$TotalTrans)/13,sum(springppt$TotalTrans)/13,sum(springppt$TotalTrans)/13,sum(springppt$TotalTrans)/13,0,0,sum(springppt$TotalTrans)/13,sum(springppt$TotalTrans)/13,sum(springppt$TotalTrans)/13,sum(springppt$TotalTrans)/13,sum(springppt$TotalTrans)/13,sum(springppt$TotalTrans)/13,0), "Purchases"= c(0,sum(springppt$TotalPurch)/13,sum(springppt$TotalPurch)/13,sum(springppt$TotalPurch)/13,sum(springppt$TotalPurch)/13,sum(springppt$TotalPurch)/13,sum(springppt$TotalPurch)/13,sum(springppt$TotalPurch)/13,0,0,sum(springppt$TotalPurch)/13,sum(springppt$TotalPurch)/13,sum(springppt$TotalPurch)/13,sum(springppt$TotalPurch)/13,sum(springppt$TotalPurch)/13,sum(springppt$TotalPurch)/13,0))

sprnullconsistentprob <- data.frame("Week"=1:17, "Probability"=c(0,1/13,1/13,1/13,1/13,1/13,1/13,1/13,0,0,1/13,1/13,1/13,1/13,1/13,1/13,0))

fallnullconsistent <- data.frame("Week"=1:16, "Transactions"= c(0,sum(fallppt$TotalTrans)/12,sum(fallppt$TotalTrans)/12,sum(fallppt$TotalTrans)/12,sum(fallppt$TotalTrans)/12,sum(fallppt$TotalTrans)/12,sum(fallppt$TotalTrans)/12,0,sum(fallppt$TotalTrans)/12,sum(fallppt$TotalTrans)/12,sum(fallppt$TotalTrans)/12,sum(fallppt$TotalTrans)/12,0,sum(fallppt$TotalTrans)/12,sum(fallppt$TotalTrans)/12,0), "Purchases"= c(0,sum(fallppt$TotalPurch)/12,sum(fallppt$TotalPurch)/12,sum(fallppt$TotalPurch)/12,sum(fallppt$TotalPurch)/12,sum(fallppt$TotalPurch)/12,sum(fallppt$TotalPurch)/12,0,sum(fallppt$TotalPurch)/12,sum(fallppt$TotalPurch)/12,sum(fallppt$TotalPurch)/12,sum(fallppt$TotalPurch)/12,0,sum(fallppt$TotalPurch)/12,sum(fallppt$TotalPurch)/12,0))

fallnullconsistentprob <- data.frame("Week"=1:16, "Probability"=c(0,1/12,1/12,1/12,1/12,1/12,1/12,0,1/12,1/12,1/12,1/12,0,1/12,1/12,0))

ggplot(sprnullconsistent) + geom_bar(aes(x=Week, y=Transactions), stat='identity', fill = "navy", color = "black") + ggtitle("Consistent Null: Spring Transactions") + scale_x_continuous(breaks = 1:17)
ggplot(sprnullconsistent) + geom_bar(aes(x=Week, y=Purchases), stat='identity', fill = "navy", color = "black") + ggtitle("Consistent Null: Spring Expenditures") + scale_x_continuous(breaks = 1:17) + ylab("Expenditures ($)")

ggplot(fallnullconsistent) + geom_bar(aes(x=Week, y=Transactions), stat='identity', fill = "steelblue", color = "black") + ggtitle("Consistent Null: Fall Transactions") + scale_x_continuous(breaks = 1:16)
ggplot(fallnullconsistent) + geom_bar(aes(x=Week, y=Purchases), stat='identity', fill = "steelblue", color = "black") + ggtitle("Consistent Null: Fall Expenditures") + scale_x_continuous(breaks = 1:16) + ylab("Expenditures ($)")

```

```{r}
#285/518=55.02% of students believe they spend consistently (1/3 beginning, 1/3 middle, 1/3 end)
#86/518=16.60% of students believe they spend most in beginning (1/2 beginning, 1/3 middle, 1/6 end)
#147/518=28.38% of students believe they spend most at end (1/6 beginning, 1/3 middle, 1/2 end)

#Tested - Sums of spring/fall weighted expectation nulls add up to sum of purchases/transactions from spring/fall  PPT
#Note - each period represents total spending expected during that period, then divided by number of weeks in     that period (spring separated into 4/5/4, fall into 4/4/4). Since spring separated into 4/5/4, need extra weighting component to account for length of middle section. Since 5/13 = 1.25*4/13, multiply transactions/purchases in periods 1 and 3 by 0.913 and multiply transactions/purchases in period 2 by 1.174. FIGURE OUT MATH PROOF BEHIND THIS

p1springtrans <- (.5502*sum(springppt$TotalTrans)*(1/3) + .1660*sum(springppt$TotalTrans)*(1/2) + .2838*sum(springppt$TotalTrans)*(1/6))*.913
p2springtrans <- (.5502*sum(springppt$TotalTrans)*(1/3) + .1660*sum(springppt$TotalTrans)*(1/3) + .2838*sum(springppt$TotalTrans)*(1/3))*1.174
p3springtrans <- (.5502*sum(springppt$TotalTrans)*(1/3) + .1660*sum(springppt$TotalTrans)*(1/6) + .2838*sum(springppt$TotalTrans)*(1/2))*.913

p1springpurch <- (.5502*sum(springppt$TotalPurch)*(1/3) + .1660*sum(springppt$TotalPurch)*(1/2) + .2838*sum(springppt$TotalPurch)*(1/6))*.913
p2springpurch <- (.5502*sum(springppt$TotalPurch)*(1/3) + .1660*sum(springppt$TotalPurch)*(1/3) + .2838*sum(springppt$TotalPurch)*(1/3))*1.174
p3springpurch <- (.5502*sum(springppt$TotalPurch)*(1/3) + .1660*sum(springppt$TotalPurch)*(1/6) + .2838*sum(springppt$TotalPurch)*(1/2))*.913

p1springprob <- (.5502*(1/3) + .1660*(1/2) + .2838*(1/6))*.913
p2springprob <- (.5502*(1/3) + .1660*(1/3) + .2838*(1/3))*1.174
p3springprob <- (.5502*(1/3) + .1660*(1/6) + .2838*(1/2))*.913

sprnullweighted <- data.frame("Week"=1:17, "Transactions"= c(0,p1springtrans/4,p1springtrans/4,p1springtrans/4,p1springtrans/4,p2springtrans/5,p2springtrans/5,p2springtrans/5,0,0,p2springtrans/5,p2springtrans/5,p3springtrans/4,p3springtrans/4,p3springtrans/4,p3springtrans/4,0), "Purchases"= c(0,p1springpurch/4,p1springpurch/4,p1springpurch/4,p1springpurch/4,p2springpurch/5,p2springpurch/5,p2springpurch/5,0,0,p2springpurch/5,p2springpurch/5,p3springpurch/4,p3springpurch/4,p3springpurch/4,p3springpurch/4,0))

sprnullweightedprob <- data.frame("Week"=1:17, "Probability"= c(0,p1springprob/4,p1springprob/4,p1springprob/4,p1springprob/4,p2springprob/5,p2springprob/5,p2springprob/5,0,0,p2springprob/5,p2springprob/5,p3springprob/4,p3springprob/4,p3springprob/4,p3springprob/4,0))

p1falltrans <- .5502*sum(fallppt$TotalTrans)*(1/3) + .1660*sum(fallppt$TotalTrans)*(1/2) + .2838*sum(fallppt$TotalTrans)*(1/6)
p2falltrans <- .5502*sum(fallppt$TotalTrans)*(1/3) + .1660*sum(fallppt$TotalTrans)*(1/3) + .2838*sum(fallppt$TotalTrans)*(1/3)
p3falltrans <- .5502*sum(fallppt$TotalTrans)*(1/3) + .1660*sum(fallppt$TotalTrans)*(1/6) + .2838*sum(fallppt$TotalTrans)*(1/2)

p1fallpurch <- .5502*sum(fallppt$TotalPurch)*(1/3) + .1660*sum(fallppt$TotalPurch)*(1/2) + .2838*sum(fallppt$TotalPurch)*(1/6)
p2fallpurch <- .5502*sum(fallppt$TotalPurch)*(1/3) + .1660*sum(fallppt$TotalPurch)*(1/3) + .2838*sum(fallppt$TotalPurch)*(1/3)
p3fallpurch <- .5502*sum(fallppt$TotalPurch)*(1/3) + .1660*sum(fallppt$TotalPurch)*(1/6) + .2838*sum(fallppt$TotalPurch)*(1/2)

p1fallprob <- .5502*(1/3) + .1660*(1/2) + .2838*(1/6)
p2fallprob <- .5502*(1/3) + .1660*(1/3) + .2838*(1/3)
p3fallprob <- .5502*(1/3) + .1660*(1/6) + .2838*(1/2)

fallnullweighted <- data.frame("Week"=1:16, "Transactions"= c(0,p1falltrans/4,p1falltrans/4,p1falltrans/4,p1falltrans/4,p2falltrans/4,p2falltrans/4,0,p2falltrans/4,p2falltrans/4,p3falltrans/4,p3falltrans/4,0,p3falltrans/4,p3falltrans/4,0), "Purchases"= c(0,p1fallpurch/4,p1fallpurch/4,p1fallpurch/4,p1fallpurch/4,p2fallpurch/4,p2fallpurch/4,0,p2fallpurch/4,p2fallpurch/4,p3fallpurch/4,p3fallpurch/4,0,p3fallpurch/4,p3fallpurch/4,0))

fallnullweightedprob <- data.frame("Week"=1:16, "Probability"= c(0,p1fallprob/4,p1fallprob/4,p1fallprob/4,p1fallprob/4,p2fallprob/4,p2fallprob/4,0,p2fallprob/4,p2fallprob/4,p3fallprob/4,p3fallprob/4,0,p3fallprob/4,p3fallprob/4,0))

ggplot(sprnullweighted) + geom_bar(aes(x=Week, y=Transactions), stat='identity', fill = "navy", color = "black") + ggtitle("Weighted Null: Spring Transactions") + scale_x_continuous(breaks = 1:17)
ggplot(sprnullweighted) + geom_bar(aes(x=Week, y=Purchases), stat='identity', fill = "navy", color = "black") + ggtitle("Weighted Null: Spring Expenditures") + scale_x_continuous(breaks = 1:17) + ylab("Expenditures ($)")

ggplot(fallnullweighted) + geom_bar(aes(x=Week, y=Transactions), stat='identity', fill = "steelblue", color = "black") + ggtitle("Weighted Null: Fall Transactions") + scale_x_continuous(breaks = 1:16)
ggplot(fallnullweighted) + geom_bar(aes(x=Week, y=Purchases), stat='identity', fill = "steelblue", color = "black") + ggtitle("Weighted Null: Fall Expenditures") + scale_x_continuous(breaks = 1:16) + ylab("Expenditures ($)")

```

Chi Squared Models


```{r}
#Removing unwanted weeks from dataframes
sprnullconsistent <- sprnullconsistent %>% filter(Transactions != 0)
fallnullconsistent <- fallnullconsistent %>% filter(Transactions != 0)
sprnullweighted <- sprnullweighted %>% filter(Transactions != 0)
fallnullweighted <- fallnullweighted %>% filter(Transactions != 0)

sprnullconsistentprob <- sprnullconsistentprob %>% filter(Probability != 0)
fallnullconsistentprob <- fallnullconsistentprob %>% filter(Probability != 0)
sprnullweightedprob <- sprnullweightedprob %>% filter(Probability != 0)
fallnullweightedprob <- fallnullweightedprob %>% filter(Probability != 0)

springtransactions <- springtransactions %>% filter(Transactions != 0)
falltransactions <- falltransactions %>% filter(Transactions != 0)
springpurchases <- springpurchases %>% filter(TotalPurch != 0)
fallpurchases <- fallpurchases %>% filter(TotalPurch != 0)

```

```{r}
#Two Nulls Against One Another
chisq.test(sprnullweighted$Transactions, p = sprnullconsistentprob$Probability)
chisq.test(sprnullweighted$Purchases, p = sprnullconsistentprob$Probability)
chisq.test(fallnullweighted$Transactions, p = fallnullconsistentprob$Probability)
chisq.test(fallnullweighted$Purchases, p = fallnullconsistentprob$Probability)

```

```{r}
#Spring Transactions Chi Squared

chisq.test(springtransactions$Transactions, p = sprnullconsistentprob$Probability, simulate.p.value = FALSE)
chisq.test(springtransactions$Transactions, p = sprnullweightedprob$Probability, simulate.p.value = FALSE)
```

```{r}
#Spring Purchases Chi Squared
chisq.test(springpurchases$TotalPurch, p = sprnullconsistentprob$Probability)
chisq.test(springpurchases$TotalPurch, p = sprnullweightedprob$Probability)

```

```{r}
#Fall Transactions Chi Squared
chisq.test(falltransactions$Transactions, p = fallnullconsistentprob$Probability)
chisq.test(falltransactions$Transactions, p = fallnullweightedprob$Probability)
```

```{r}
#Fall Purchases Chi Squared
chisq.test(fallpurchases$TotalPurch, p = fallnullconsistentprob$Probability)
chisq.test(fallpurchases$TotalPurch, p = fallnullweightedprob$Probability)
```
